### ISSUE TITLE
高度固定

### ISSUE THREAD

**Issue by huangping35** [CoderZhuXH/XHWebImageAutoSize#4]
如果是高度固定，这个要怎么办

**Comment by CoderZhuXH** [comment]
可以通过这个接口,获取缓存图片尺寸,计算宽度
+(CGSize )imageSizeFromCacheForURL:(NSURL *)url

最近较忙,有时间的话,会增加一个直接获取宽度接口..

**Comment by Beyond-Chao** [comment]
@huangping35  如果cell的高度固定，可能你就用不了这个工具了，你可以设置imageView的contentMode为 UIViewContentModeScaleAspectFit 或者 UIViewContentModeScaleAspectFill，在保证图片比例不变的情况下实现你想要的效果。
