### ISSUE TITLE
获取图片高度,得到的是estimateHeight

### ISSUE THREAD

**Issue by ChaosLcc** [CoderZhuXH/XHWebImageAutoSize#8]
- 自己的代码

```
CGFloat height = [XHWebImageAutoSize imageHeightForURL:[NSURL URLWithString:img] layoutWidth:SCREEN_WIDTH - 20 estimateHeight:100];
```

![image](https://user-images.githubusercontent.com/16434139/45289772-96e57080-b520-11e8-875c-eb6ab6534773.png)

- 最终结果一直都是estimateHeight  100这个高度, 是我漏掉了什么吗?

**Comment by CoderZhuXH** [comment]
![wx20180912-091921](https://user-images.githubusercontent.com/15043466/45396257-09fbfd80-b66d-11e8-999f-b64da1012d56.png)

**Comment by guochao285575** [comment]
OK, 我已经解决了,   忘了关闭了,感谢您的回复

**Comment by ChaosLcc** [comment]
@CoderZhuXH OK, 我已经解决了,   忘了关闭了,感谢您的回复

**Comment by MrWithGuo** [comment]
在没解决的？我也遇到这种问题了
